export const QuoteCategory = {
    SLOW: 'slow',
    FAST: 'fast',
    RANDOM: 'random'
} as const;

export type QuoteCategory = typeof QuoteCategory[keyof typeof QuoteCategory];

export interface Quote {
    text: string;
    categories: QuoteCategory[];
}

export const QUOTES: Quote[] = [
    // 1. Random / Neutral
    { text: "Full Focus", categories: [QuoteCategory.RANDOM] },
    { text: "Eyes on the Prize", categories: [QuoteCategory.RANDOM] },
    { text: "One Line at a Time", categories: [QuoteCategory.RANDOM] },
    { text: "Only Forward", categories: [QuoteCategory.RANDOM] },
    { text: "Let the Words Flow", categories: [QuoteCategory.RANDOM] },
    { text: "Zero Distractions", categories: [QuoteCategory.RANDOM] },
    { text: "All In", categories: [QuoteCategory.RANDOM] },
    { text: "Keep Typing", categories: [QuoteCategory.RANDOM] },
    { text: "Write Fierce", categories: [QuoteCategory.RANDOM] },
    { text: "Silence the Inner Critic", categories: [QuoteCategory.RANDOM] },
    { text: "The Words Are Yours", categories: [QuoteCategory.RANDOM] },
    { text: "Flow Like Water", categories: [QuoteCategory.RANDOM] },
    { text: "Ink the Unseen", categories: [QuoteCategory.RANDOM] },
    { text: "Shape the Chaos", categories: [QuoteCategory.RANDOM] },
    { text: "First Draft Freedom", categories: [QuoteCategory.RANDOM] },
    { text: "Type. Don’t Think.", categories: [QuoteCategory.RANDOM] },
    { text: "Lines in Motion", categories: [QuoteCategory.RANDOM] },
    { text: "Let the Page Breathe", categories: [QuoteCategory.RANDOM] },
    { text: "Words Over Thought", categories: [QuoteCategory.RANDOM] },
    { text: "Forward", categories: [QuoteCategory.RANDOM] },
    { text: "Go!", categories: [QuoteCategory.RANDOM] },
    { text: "Focus", categories: [QuoteCategory.RANDOM] },
    { text: "Commit", categories: [QuoteCategory.RANDOM] },
    { text: "Sprint", categories: [QuoteCategory.RANDOM] },
    { text: "Unstoppable", categories: [QuoteCategory.RANDOM] },
    { text: "Zero Edit", categories: [QuoteCategory.RANDOM] },
    { text: "Full Speed", categories: [QuoteCategory.RANDOM] },
    { text: "No Looking Back", categories: [QuoteCategory.RANDOM] },
    { text: "Let It Pour", categories: [QuoteCategory.RANDOM] },
    { text: "Ride the Flow", categories: [QuoteCategory.RANDOM] },
    { text: "Write Like Nobody’s Watching", categories: [QuoteCategory.RANDOM] },
    { text: "The Page Is Yours", categories: [QuoteCategory.RANDOM] },
    { text: "Don’t Stop, Don’t Blink", categories: [QuoteCategory.RANDOM] },
    { text: "Chase the Momentum", categories: [QuoteCategory.RANDOM] },
    { text: "Momentum On", categories: [QuoteCategory.RANDOM] },
    { text: "Eyes Forward", categories: [QuoteCategory.RANDOM] },
    { text: "Words in Motion", categories: [QuoteCategory.RANDOM] },
    { text: "Keep Rolling", categories: [QuoteCategory.RANDOM] },
    { text: "Stay in the Zone", categories: [QuoteCategory.RANDOM] },

    // 2. Fast Pace
    { text: "You’re On Fire!", categories: [QuoteCategory.FAST] },
    { text: "Burn Through the Page", categories: [QuoteCategory.FAST] },
    { text: "Beat Your Last Sprint", categories: [QuoteCategory.FAST] },
    { text: "Maximum Momentum", categories: [QuoteCategory.FAST] },
    { text: "Push Through", categories: [QuoteCategory.FAST] },
    { text: "No Pauses Allowed", categories: [QuoteCategory.FAST] },
    { text: "Forward Only", categories: [QuoteCategory.FAST] },
    { text: "The Clock Is Ticking", categories: [QuoteCategory.FAST] },
    { text: "Don’t Break the Chain", categories: [QuoteCategory.FAST] },
    { text: "Keep the Speed", categories: [QuoteCategory.FAST] },
    { text: "Fast and Furious", categories: [QuoteCategory.FAST] },
    { text: "Ride the Lightning", categories: [QuoteCategory.FAST] },
    { text: "Flow Unleashed", categories: [QuoteCategory.FAST] },
    { text: "Keep Pushing", categories: [QuoteCategory.FAST] },
    { text: "Words at Warp Speed", categories: [QuoteCategory.FAST] },
    { text: "Blaze Ahead", categories: [QuoteCategory.FAST] },
    { text: "Don’t Slow Down", categories: [QuoteCategory.FAST] },
    { text: "Full Throttle", categories: [QuoteCategory.FAST] },
    { text: "Turbo Mode", categories: [QuoteCategory.FAST] },
    { text: "Lightning Fingers", categories: [QuoteCategory.FAST] },
    { text: "Rapid Fire", categories: [QuoteCategory.FAST] },
    { text: "Peak Flow", categories: [QuoteCategory.FAST] },
    { text: "Words on Fire", categories: [QuoteCategory.FAST] },
    { text: "Keep Up the Pace", categories: [QuoteCategory.FAST] },
    { text: "Maximum Focus", categories: [QuoteCategory.FAST] },
    { text: "High Gear", categories: [QuoteCategory.FAST] },
    { text: "Full Momentum", categories: [QuoteCategory.FAST] },
    { text: "No Stopping Now", categories: [QuoteCategory.FAST] },
    { text: "Stay Ahead", categories: [QuoteCategory.FAST] },
    { text: "On a Roll", categories: [QuoteCategory.FAST] },

    // 3. Slow Pace
    { text: "Keep Moving", categories: [QuoteCategory.SLOW] },
    { text: "One Word at a Time", categories: [QuoteCategory.SLOW] },
    { text: "You Got This", categories: [QuoteCategory.SLOW] },
    { text: "Steady Flow", categories: [QuoteCategory.SLOW] },
    { text: "Don’t Overthink", categories: [QuoteCategory.SLOW] },
    { text: "Slow and Steady", categories: [QuoteCategory.SLOW] },
    { text: "Focused Steps", categories: [QuoteCategory.SLOW] },
    { text: "Let Ideas Come", categories: [QuoteCategory.SLOW] },
    { text: "Relax, Write", categories: [QuoteCategory.SLOW] },
    { text: "Keep the Rhythm", categories: [QuoteCategory.SLOW] },
    { text: "Breath and Type", categories: [QuoteCategory.SLOW] },
    { text: "Don’t Rush", categories: [QuoteCategory.SLOW] },
    { text: "Gentle Momentum", categories: [QuoteCategory.SLOW] },
    { text: "Let the Words Find You", categories: [QuoteCategory.SLOW] },
    { text: "Maintain Focus", categories: [QuoteCategory.SLOW] },
    { text: "Stay Calm, Write On", categories: [QuoteCategory.SLOW] },
    { text: "Steady Fingers", categories: [QuoteCategory.SLOW] },
    { text: "Keep It Simple", categories: [QuoteCategory.SLOW] },
    { text: "Words Will Come", categories: [QuoteCategory.SLOW] },
    { text: "Flow at Your Pace", categories: [QuoteCategory.SLOW] },
    { text: "Write Softly, Write True", categories: [QuoteCategory.SLOW] },
    { text: "Smooth Sailing", categories: [QuoteCategory.SLOW] },
    { text: "One Line Forward", categories: [QuoteCategory.SLOW] },
    { text: "Don’t Force It", categories: [QuoteCategory.SLOW] },
    { text: "Quiet Focus", categories: [QuoteCategory.SLOW] },
    { text: "Keep Typing, Slowly", categories: [QuoteCategory.SLOW] },
    { text: "Stay in the Zone", categories: [QuoteCategory.SLOW] },
    { text: "Calm and Productive", categories: [QuoteCategory.SLOW] },
    { text: "The Page Awaits", categories: [QuoteCategory.SLOW] },
    { text: "Keep Going", categories: [QuoteCategory.SLOW] }
];
